# Generated by Django 4.0 on 2023-10-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='carriers/')),
                ('name', models.CharField(max_length=255)),
                ('api_base_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrierStateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_state', models.CharField(max_length=255)),
                ('company_website_state', models.CharField(max_length=255)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carrier.carrier')),
            ],
        ),
    ]
