# Generated by Django 4.0 on 2023-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='carrierstateconversion',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='carrier',
            name='logo',
            field=models.ImageField(default='carrier_logos/default_logo.png', null=True, upload_to='carrier_logos/'),
        ),
    ]
