# Use Ubuntu 20.04 as the base image
FROM ubuntu:20.04

# Update the package list and install required dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common

# Add the deadsnakes PPA for Python 3.11
RUN add-apt-repository ppa:deadsnakes/ppa

# Update the package list again and install Python 3.11
RUN apt-get update && apt-get install -y \
    python3.11

# Install wget
RUN apt-get install -y wget

# Install pip for Python 3.11
RUN apt-get install -y python3.11-distutils
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3.11 get-pip.py

# Add Python 3.11 executable to PATH
#ENV PATH="/usr/bin/python3.11:${PATH}"


# Clean up to reduce the image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the default Python version to Python 3.11
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
RUN update-alternatives --config python3


# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file and install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the Django project files into the container
COPY . /app/

# Expose the port the application will run on
EXPOSE 8000

# SET THE WORKING THE DJANGO APP PATH 
WORKDIR /app/maw

# Run Django migrations and start the application
CMD ["python3.11", "manage.py", "runserver","0.0.0.0:8000"]