# Generated by Django 4.0 on 2022-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaction',
            name='state',
            field=models.JSONField(default="{'state':'working'}"),
        ),
    ]
