# Generated by Django 4.0 on 2022-11-24 13:32

import WebApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0002_alter_orderaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaction',
            name='state',
            field=models.JSONField(default=WebApi.models.get_default_state),
        ),
    ]
