# Generated by Django 4.0 on 2022-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0003_alter_orderaction_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afexmonitororder',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='loxboxmonitororder',
            name='order_id',
            field=models.IntegerField(unique=True),
        ),
    ]
