# Generated by Django 4.0 on 2022-11-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0004_alter_afexmonitororder_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selected_all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selected_all', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApi.city')),
            ],
        ),
        migrations.CreateModel(
            name='LoxboxCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApi.delegation')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='loxbox_cities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApi.loxboxcities'),
        ),
    ]
