# Generated by Django 4.0 on 2022-12-02 10:32

import WebApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0005_city_delegation_loxboxcities_locality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoxboxAreasSelectorProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_working', models.BooleanField(default=False)),
                ('progress', models.JSONField(default=WebApi.models.get_lx_areas_selector_proc_default_state)),
            ],
        ),
    ]
