# Generated by Django 4.0 on 2022-12-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0006_loxboxareasselectorprocess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='selected_all',
            new_name='selected',
        ),
        migrations.RenameField(
            model_name='delegation',
            old_name='selected_all',
            new_name='selected',
        ),
        migrations.RenameField(
            model_name='loxboxcities',
            old_name='selected_all',
            new_name='selected',
        ),
    ]
