# Generated by Django 4.0 on 2023-01-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0008_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='afex_api_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='afex_client_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
