# Generated by Django 4.0 on 2023-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0009_setting_afex_api_key_setting_afex_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='loxbox_api_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
