# Generated by Django 4.0 on 2023-06-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0010_setting_loxbox_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='afexmonitororder',
            name='barcode',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
