# Generated by Django 4.0 on 2023-10-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApi', '0011_afexmonitororder_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afexmonitororder',
            name='manifest_date',
        ),
    ]
