# Generated by Django 4.0 on 2023-10-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='icon_logo.png', upload_to='')),
                ('api_base_url', models.URLField(max_length=100)),
                ('api_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWebsiteState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_id', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.companyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='loading_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_loading_state', to='Account.companywebsitestate'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='post_submit_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_post_submit_state', to='Account.companywebsitestate'),
        ),
    ]
