# Generated by Django 4.0 on 2023-10-18 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_companyprofile_loading_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='loading_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_order_loading_state', to='Account.companyorderstate'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='post_submit_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_order_post_submit_state', to='Account.companyorderstate'),
        ),
    ]
