# Generated by Django 4.0 on 2023-10-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_companyprofile_loading_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='loading_state',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='post_submit_state',
        ),
    ]
