# Generated by Django 4.2 on 2023-11-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_companyprofile_logo_alter_companyprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyorderstate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
